-- Estrutura inicial do banco, refletindo exatamente o schema já gerado pelo
-- Hibernate (ddl-auto=update) até aqui. A partir desta migration, o schema
-- passa a ser controlado pelo Flyway; o Hibernate só valida (ddl-auto=validate).

CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    email VARCHAR(180) NOT NULL,
    senha_hash VARCHAR(255) NOT NULL,
    criado_em TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_usuarios_email UNIQUE (email)
);

CREATE TABLE lotes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identificacao VARCHAR(120) NOT NULL,
    criado_em TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    usuario_id BIGINT NOT NULL,
    CONSTRAINT fk_lotes_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id)
);

CREATE TABLE mensagens_contato (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    email VARCHAR(180) NOT NULL,
    tipo VARCHAR(30) NOT NULL,
    mensagem VARCHAR(2000) NOT NULL,
    enviado_em TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE TABLE categorias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    ordem INTEGER NOT NULL
);

CREATE TABLE perguntas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoria_id BIGINT NOT NULL,
    enunciado VARCHAR(500) NOT NULL,
    ordem INTEGER NOT NULL,
    CONSTRAINT fk_perguntas_categoria FOREIGN KEY (categoria_id) REFERENCES categorias (id)
);

CREATE TABLE opcoes_resposta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pergunta_id BIGINT NOT NULL,
    texto VARCHAR(255) NOT NULL,
    peso INTEGER NOT NULL,
    ordem INTEGER NOT NULL,
    CONSTRAINT fk_opcoes_resposta_pergunta FOREIGN KEY (pergunta_id) REFERENCES perguntas (id)
);

CREATE TABLE triagens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lote_id BIGINT NOT NULL,
    pontuacao_total INTEGER NOT NULL,
    cenario VARCHAR(20) NOT NULL,
    respondido_em TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_triagens_lote FOREIGN KEY (lote_id) REFERENCES lotes (id)
);

CREATE TABLE respostas_triagem (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    triagem_id BIGINT NOT NULL,
    pergunta_id BIGINT NOT NULL,
    opcao_resposta_id BIGINT NOT NULL,
    peso_registrado INTEGER NOT NULL,
    CONSTRAINT fk_respostas_triagem_triagem FOREIGN KEY (triagem_id) REFERENCES triagens (id),
    CONSTRAINT fk_respostas_triagem_pergunta FOREIGN KEY (pergunta_id) REFERENCES perguntas (id),
    CONSTRAINT fk_respostas_triagem_opcao FOREIGN KEY (opcao_resposta_id) REFERENCES opcoes_resposta (id),
    CONSTRAINT uk_respostas_triagem_triagem_pergunta UNIQUE (triagem_id, pergunta_id)
);
